/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishapp;

/**
 *
 * @author coreilly
 */
public class MainFrame extends javax.swing.JFrame {

        
    //create a new DataStore object. 
    DataStore ds = new DataStore();
    
    
    public MainFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFishInfo = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DugongButton = new javax.swing.JButton();
        HumpbackedWhaleButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BandedSeaKraitButton = new javax.swing.JButton();
        GreenSeaTurtleButton = new javax.swing.JButton();
        OliveRidelyTurtleButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        WhaleSharkButton = new javax.swing.JButton();
        HammerheadSharkButton = new javax.swing.JButton();
        TigerSharkButton = new javax.swing.JButton();
        LemonSharkButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ParrotFishButton = new javax.swing.JButton();
        WrasseButton = new javax.swing.JButton();
        CodButton = new javax.swing.JButton();
        TroutButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OctopusButton = new javax.swing.JButton();
        CuttlefishButton = new javax.swing.JButton();
        SquidButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Fish App");

        txtFishInfo.setColumns(20);
        txtFishInfo.setRows(5);
        txtFishInfo.setText("Fish Info");
        jScrollPane1.setViewportView(txtFishInfo);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mammals");

        DugongButton.setText("Dugong");
        DugongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DugongButtonActionPerformed(evt);
            }
        });

        HumpbackedWhaleButton.setText("Hump backed Whale");
        HumpbackedWhaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumpbackedWhaleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(DugongButton)
                        .addGap(18, 18, 18)
                        .addComponent(HumpbackedWhaleButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DugongButton)
                    .addComponent(HumpbackedWhaleButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Reptiles");

        BandedSeaKraitButton.setText("Banded Sea Krait");
        BandedSeaKraitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandedSeaKraitButtonActionPerformed(evt);
            }
        });

        GreenSeaTurtleButton.setText("Green Sea Turtle");
        GreenSeaTurtleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenSeaTurtleButtonActionPerformed(evt);
            }
        });

        OliveRidelyTurtleButton.setText("Olive Ridely Turtle");
        OliveRidelyTurtleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OliveRidelyTurtleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GreenSeaTurtleButton)
                    .addComponent(BandedSeaKraitButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OliveRidelyTurtleButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BandedSeaKraitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GreenSeaTurtleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(OliveRidelyTurtleButton)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Cartilaginous Fish");

        WhaleSharkButton.setText("Whale Shark");
        WhaleSharkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhaleSharkButtonActionPerformed(evt);
            }
        });

        HammerheadSharkButton.setText("Hammerhead Shark");
        HammerheadSharkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HammerheadSharkButtonActionPerformed(evt);
            }
        });

        TigerSharkButton.setText("Tiger Shark");
        TigerSharkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TigerSharkButtonActionPerformed(evt);
            }
        });

        LemonSharkButton.setText("Lemon Shark");
        LemonSharkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LemonSharkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(WhaleSharkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LemonSharkButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TigerSharkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HammerheadSharkButton)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WhaleSharkButton)
                    .addComponent(LemonSharkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TigerSharkButton)
                    .addComponent(HammerheadSharkButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ray-finned Fish");

        ParrotFishButton.setText("Parrot Fish");
        ParrotFishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParrotFishButtonActionPerformed(evt);
            }
        });

        WrasseButton.setText("Wrasse");
        WrasseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WrasseButtonActionPerformed(evt);
            }
        });

        CodButton.setText("Cod");
        CodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodButtonActionPerformed(evt);
            }
        });

        TroutButton.setText("Trout");
        TroutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TroutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(TroutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WrasseButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(CodButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ParrotFishButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParrotFishButton)
                    .addComponent(CodButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WrasseButton)
                    .addComponent(TroutButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 0, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cephalopods");

        OctopusButton.setText("Octopus");
        OctopusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctopusButtonActionPerformed(evt);
            }
        });

        CuttlefishButton.setText("Cuttlefish");
        CuttlefishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuttlefishButtonActionPerformed(evt);
            }
        });

        SquidButton.setText("Squid");
        SquidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquidButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CuttlefishButton)
                            .addComponent(OctopusButton)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(SquidButton))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OctopusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuttlefishButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SquidButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ResetButton.setBackground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Animal Image");
        jLabel7.setMaximumSize(new java.awt.Dimension(250, 204));
        jLabel7.setMinimumSize(new java.awt.Dimension(250, 204));
        jLabel7.setPreferredSize(new java.awt.Dimension(250, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)))
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DugongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DugongButtonActionPerformed
        txtFishInfo.setText(ds.increment("dugong"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dugong.jpg")));
    }//GEN-LAST:event_DugongButtonActionPerformed

    private void HumpbackedWhaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumpbackedWhaleButtonActionPerformed
        txtFishInfo.setText(ds.increment("humpBackedWhale"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/humpbackedwhale.jpg")));
    }//GEN-LAST:event_HumpbackedWhaleButtonActionPerformed

    private void BandedSeaKraitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandedSeaKraitButtonActionPerformed
        txtFishInfo.setText(ds.increment("bandedSeaKrait"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bandedSeaKrait.jpg")));
    }//GEN-LAST:event_BandedSeaKraitButtonActionPerformed

    private void GreenSeaTurtleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenSeaTurtleButtonActionPerformed
        txtFishInfo.setText(ds.increment("greenSeaTurtle"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/greenSeaTurtle.jpg")));
    }//GEN-LAST:event_GreenSeaTurtleButtonActionPerformed

    private void OliveRidelyTurtleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OliveRidelyTurtleButtonActionPerformed
        txtFishInfo.setText(ds.increment("oliveRidelyTurtle"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oliveRidelyTurtle.jpg")));
    }//GEN-LAST:event_OliveRidelyTurtleButtonActionPerformed

    private void WhaleSharkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhaleSharkButtonActionPerformed
        txtFishInfo.setText(ds.increment("whaleShark"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whaleShark.jpg")));
    }//GEN-LAST:event_WhaleSharkButtonActionPerformed

    private void HammerheadSharkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HammerheadSharkButtonActionPerformed
        txtFishInfo.setText(ds.increment("hammerheadShark"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hammerheadShark.jpg")));
    }//GEN-LAST:event_HammerheadSharkButtonActionPerformed

    private void TigerSharkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigerSharkButtonActionPerformed
        txtFishInfo.setText(ds.increment("tigerShark"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tigerShark.jpg")));
    }//GEN-LAST:event_TigerSharkButtonActionPerformed

    private void LemonSharkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LemonSharkButtonActionPerformed
        txtFishInfo.setText(ds.increment("lemonShark"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lemonShark.jpg")));
    }//GEN-LAST:event_LemonSharkButtonActionPerformed

    private void ParrotFishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParrotFishButtonActionPerformed
        txtFishInfo.setText(ds.increment("parrotFish"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parrotFish.jpg")));
    }//GEN-LAST:event_ParrotFishButtonActionPerformed

    private void WrasseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WrasseButtonActionPerformed
        txtFishInfo.setText(ds.increment("wrasse"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrasse.jpg")));
    }//GEN-LAST:event_WrasseButtonActionPerformed

    private void OctopusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctopusButtonActionPerformed
        txtFishInfo.setText(ds.increment("octopus"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/octopus.jpg")));
    }//GEN-LAST:event_OctopusButtonActionPerformed

    private void CuttlefishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuttlefishButtonActionPerformed
        txtFishInfo.setText(ds.increment("cuttlefish"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuttlefish.jpg")));
    }//GEN-LAST:event_CuttlefishButtonActionPerformed

    private void SquidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquidButtonActionPerformed
        txtFishInfo.setText(ds.increment("squid"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squid.jpg")));
    }//GEN-LAST:event_SquidButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        txtFishInfo.setText(ds.increment("reset"));
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void CodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodButtonActionPerformed
        /* we call the increment() method of the data store object and pass a string to it.
        The increment method adds 1 to the number of cod and returns a string containing
        information about the fish. We display the string in the txtFishInfo text box.
        See comments in the DataStore class for more information about the increment() method.
        */
        txtFishInfo.setText(ds.increment("cod"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cod.jpg")));
    }//GEN-LAST:event_CodButtonActionPerformed

    private void TroutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TroutButtonActionPerformed

        txtFishInfo.setText(ds.increment("trout"));
        jLabel7.setText("");
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trout.jpg")));
    }//GEN-LAST:event_TroutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BandedSeaKraitButton;
    private javax.swing.JButton CodButton;
    private javax.swing.JButton CuttlefishButton;
    private javax.swing.JButton DugongButton;
    private javax.swing.JButton GreenSeaTurtleButton;
    private javax.swing.JButton HammerheadSharkButton;
    private javax.swing.JButton HumpbackedWhaleButton;
    private javax.swing.JButton LemonSharkButton;
    private javax.swing.JButton OctopusButton;
    private javax.swing.JButton OliveRidelyTurtleButton;
    private javax.swing.JButton ParrotFishButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SquidButton;
    private javax.swing.JButton TigerSharkButton;
    private javax.swing.JButton TroutButton;
    private javax.swing.JButton WhaleSharkButton;
    private javax.swing.JButton WrasseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtFishInfo;
    // End of variables declaration//GEN-END:variables

    
}
